export {default as Skills} from "./Skills"
export {default as About} from "./About"
export {default as Navigation} from "./Navigation"
export {default as MyPic} from "./MyPic"
export {default as Contact} from "./Contact"
